Module12 task1
htmlacademy-javascript/1713127-keksobooking-23 pull request #11
Opened 2021-07-05 09:51 UTC by Niqp

2021-07-05 15:52 UTC, balesniy requested changes
посмотри на критерии Б23 и Б24, они базовые и нам нужно их учесть к защите проекта

2021-07-05 15:52 UTC, balesniy commented on js/generate-cards.js
> +      cards.forEach((value,index) => {
тут удобнее map вместо forEach+push

2021-07-05 15:52 UTC, balesniy commented on js/form-validation.js
> +      preview.src = reader.result;
при сбросе формы нужно очистить превью, и не забыть про поле "фотографии помещения"

2021-07-05 15:52 UTC, balesniy commented on js/form.js
> +    return filter.value !== 'any' ? filter.value === string : true;
выражение можно упростить см https://up.htmlacademy.ru/javascript/23/criteries#d18 и 'any' нужно оформить в константу

2021-07-05 15:52 UTC, balesniy commented on js/form.js
> +      if (filter.value === 'middle') { return value >= PRICE_TYPES.low && value <= PRICE_TYPES.high;}
названия диапазонов нужно оформить в константы

2021-07-05 15:52 UTC, balesniy commented on js/form.js
> +    } else {return true;}
Д18

2021-07-05 15:52 UTC, balesniy commented on js/form.js
> +    cards = cards.filter((element) => element.data.offer.features !== undefined ? element.data.offer.features.some((value) => value === feature.value) : false);
Д18

2021-07-05 15:52 UTC, balesniy commented on js/form.js
> +    if (value.checked === true) {
https://up.htmlacademy.ru/javascript/23/criteries#d16 и тут можно вместо forEach использовать filter или css селектор

2021-07-05 15:52 UTC, balesniy commented on js/form.js
> +  const cardsByPrice = filterByPrice(cardsByType,filterPrice,'price');
хорошее рабочее решение, но не проходит по критериям оптимальности, нам нужно исключить лишние циклы и остановить поиск подходящих по достижению 10 элементов, для этого нужно собрать фильтрующие функции в одну, и запускать все проверки для каждого элемента отдельно, плюс придется реализовать свою кастомную версию filter, которая сможет остановить перебор элементов

2021-07-07 21:02 UTC, balesniy approved these changes

2021-07-07 21:02 UTC, balesniy commented on js/utils.js
> +  function onKeyPress (evt) {
если функция не использует this то лучше использовать стрелочную

2021-07-07 21:02 UTC, balesniy commented on js/utils.js
> +    timeoutId = setTimeout(() => callback.apply(this, rest), DEBOUNCE_DELAY);
у стрелочной this потеряется

2021-07-07 21:02 UTC, merged

2021-07-07 21:25 UTC, Niqp commented on js/utils.js
> +  function onKeyPress (evt) {
в ответах на вопросы нам писали, что при взаимном вызове функций можно описать функционально для всплытыя. Лучше оставить, как было, с присваиванием null в начале, чтобы линтер не ругался?

2021-07-08 08:56 UTC, balesniy commented on js/utils.js
> +  function onKeyPress (evt) {
если авторы отвечали, то лучше так оставить, раз тут все ради линтера)